### ISSUE TITLE
Unable to return primitives from request

### ISSUE THREAD

**Issue by dylinmaust** [vinguan/restion#4]
I like your library but there's one issue (that I've discovered thus far) holding me back from using it.

I'm unable to execute a request and serialize the response to a primitive type, e.g. integer. Assume that _client below is an instance of `RestionClient`and that request is an instance of `RestionRequest.`

`var newId = await _client.ExecuteRequestAsync<int>(request)`

..does not compile because the response is constrained to instances of a class (defined in `IRestionClient` interface):

`Task<IRestionResponse<TResponseContent>> ExecuteRequestAsync<TResponseContent>(IRestionRequest restionRequest) where TResponseContent : class;`

Am I overlooking something? 
Thanks.

**Comment by vinguan** [comment]
@TimeBomb006 Restion follows [https://www.ietf.org/rfc/rfc4627.txt](RFC-4627), in order to deserialize a response you should pass a Class. You can create a class like :
`public class NewIdResponse 
{`
`public int NewId { get; set; }`
`}`

and then

 `var newIdResponse = await _client.ExecuteRequestAsync<NewIdResponse>(request);`
  `var newId = newIdResponse.NewId;`

This should anchieve what you want.
 Let me now if it worked.
